title: "Sections"
description: |
  Big chunks of content that can stand by themselves.

patterns:
  about-me:
    title: "Highlight"
    description: |
      The highlight section should be used for any important stand-alone sections that include a title, subtitle, paragraph, and call-to-action.
    fields:
      - name: heading
        type: string
        example: "Hi! I’m Delphine."
      - name: subheading
        type: string
        example: "Graphic designer.<br> Illustrator.<br> Printmaker. <br>Cat enthusiast."
        required: false
      - name: paragraph-1
        type: string
        example: "When I work, I’m always chasing the <em>wow</em>. Everything about design gives me satisfaction — from creating entire brand identities, to nailing the perfect kerning on the smallest subheading."
      - name: paragraph-2
        type: string
        example: "But nothing gives me a better feeling than seeing someone excited about what I’ve created — every design is an opportunity to get someone to say <em>wow</em>. That’s the goal, every time."
        required: false
      - name: button_text
        type: string
        example: "Say Hello"
      - name: button_link
        type: url
        example: "#"
  left-text-block:
    title: "Text Left"
    description: |
      This text block should be used for short, descriptive paragraphs of text on project pages. It should be alternated with the <em>Text Right</em> pattern to add visual interest as you move down the page.
    fields:
    - name: title
      type: string
      example: "Project Brief"
    - name: text
      type: string
      example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae dignissim libero, at pharetra nulla. Curabitur imperdiet vitae orci ut aliquet. Vivamus viverra vestibulum venenatis. Phasellus quis est lorem. Fusce faucibus eget nulla vel lobortis. Aliquam rhoncus, sapien quis posuere ultrices, mauris nisl molestie lorem, vel porttitor purus ipsum vel massa. Pellentesque vitae odio posuere, bibendum quam non, dictum nunc. Aenean mollis metus arcu, vel scelerisque ante ornare eu."
  right-text-block:
    title: "Text Right"
    description: |
      This text block should be used for short, descriptive paragraphs of text on project pages. It should be alternated with the <em>Text Left</em> pattern (with text left always appearing first) to add visual interest as you move down the page.
    fields:
    - name: title
      type: string
      example: "Concept"
    - name: text
      type: string
      example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae dignissim libero, at pharetra nulla. Curabitur imperdiet vitae orci ut aliquet. Vivamus viverra vestibulum venenatis. Phasellus quis est lorem. Fusce faucibus eget nulla vel lobortis. Aliquam rhoncus, sapien quis posuere ultrices, mauris nisl molestie lorem, vel porttitor purus ipsum vel massa. Pellentesque vitae odio posuere, bibendum quam non, dictum nunc. Aenean mollis metus arcu, vel scelerisque ante ornare eu."
